# -*- coding: utf-8 -*-
"""Dietify.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Gh5qAPig3LRBFUwfHZFqupAlCS39W-j
"""

!pip -q install openai
!pip -q install gradio
!pip -q install Flask

import os
from flask import Flask, jsonify, request
import openai

app = Flask(__name__)

# Set OpenAI API Key
openai.api_key = "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"

def get_diet_suggestion(message):
    prompt = "suggest an indian diet with the following conditions " + message
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=1,
        max_tokens=1000,
        top_p=1,
        frequency_penalty=0,
        presence_penalty=0
    )
    return response.choices[0].message.content

@app.route('/suggest_diet', methods=['POST'])
def suggest_diet():
    data = request.get_json()
    message = data.get('message', '')
    suggestion = get_diet_suggestion(message)
    return jsonify({"suggestion": suggestion})

if __name__ == '__main__':
    app.run(debug=True)

